=== soravroyal/EPRTR/trunk_obsolete_BM/WebAppCode/Test/PerformanceTester/TestRunData.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--W3C Schema generated by XMLSpy v2008 rel. 2 (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:complexType name="T_Threads">
		<xs:sequence>
			<xs:element ref="Thread" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element ref="ThreadRef" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="T_Thread">
		<xs:sequence>
			<xs:element ref="Tasks"/>
		</xs:sequence>
		<xs:attribute ref="name" use="required"/>
		<xs:attribute ref="Id"/>
		<xs:attribute ref="ThreadCopies"/>
	</xs:complexType>
	<xs:complexType name="DatabaseJob" mixed="true">
		<xs:sequence>
			<xs:element ref="Parameters" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute ref="executionString" use="required"/>
	</xs:complexType>
	<xs:complexType name="T_Parameters">
		<xs:sequence>
			<xs:element ref="Parameter" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="T_Parameter">
		<xs:attribute ref="value" use="required"/>
		<xs:attribute ref="name" use="required"/>
		<xs:attribute ref="valueType"/>
	</xs:complexType>
	<xs:complexType name="T_Jobs">
		<xs:sequence>
			<xs:element ref="Job" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute ref="executionTime" use="required"/>
		<xs:attribute ref="commandTimeout" use="required"/>
	</xs:complexType>
	<xs:complexType name="T_Job">
		<xs:sequence>
			<xs:element ref="Threads"/>
		</xs:sequence>
		<xs:attribute ref="name" use="required"/>
		<xs:attribute ref="speedCategory"/>
	</xs:complexType>
	<xs:attribute name="value">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:attribute>
	<xs:attribute name="name">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:attribute>
	<xs:attribute name="executionString">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:attribute>
	<xs:element name="Threads" type="T_Threads"/>
	<xs:element name="Thread" type="T_Thread"/>
	<xs:element name="StoredProcedure" type="DatabaseJob"/>
	<xs:element name="Parameters" type="T_Parameters"/>
	<xs:element name="Parameter" type="T_Parameter"/>
	<xs:element name="Jobs" type="T_Jobs"/>
	<xs:element name="Job" type="T_Job"/>
	<xs:attribute name="Id" type="xs:integer"/>
	<xs:element name="ThreadRef" type="T_ThreadRef"/>
	<xs:complexType name="T_ThreadRef">
		<xs:attribute ref="Id" use="required"/>
		<xs:attribute ref="ThreadCopies"/>
	</xs:complexType>
	<xs:attribute name="speedCategory">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="FAST"/>
				<xs:enumeration value="NORMAL"/>
				<xs:enumeration value="SLOW"/>
				<xs:enumeration value="VERY SLOW"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:attribute>
	<xs:attribute name="valueType">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="int"/>
				<xs:enumeration value="string"/>
				<xs:enumeration value="double"/>
				<xs:enumeration value="datetime"/>
				<xs:enumeration value="decimal"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:attribute>
	<xs:element name="Tasks">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="StoredProcedure" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="Script" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Script" type="DatabaseJob"/>
	<xs:attribute name="executionTime" type="xs:int"/>
	<xs:attribute name="commandTimeout" type="xs:int"/>
	<xs:attribute name="ThreadCopies" type="xs:int"/>
</xs:schema>

=== soravroyal/EPRTR/tags/deploy_2011_05_19_Diffuse/WebAppCode/Test/PerformanceTester/bin/Debug/Probe.xml
<?xml version="1.0" encoding="UTF-8"?>
<Jobs executionTime="1" commandTimeout="3600" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="J:\E-PRTR Test\Performance Test\SPPerformanceTester\TestRunData.xsd">
	<Job name="One User">
		<Threads>
			<Thread name="MyThread" Id="1" ThreadCopies="1">
				<Tasks>
					<Script executionString="SELECT * FROM FACILITYSEARCH_ALL" />
				</Tasks>
			</Thread>
		</Threads>
	</Job>
	<Job name="Five Users">
		<Threads>
			<Thread name="MyThread" Id="1" ThreadCopies="5">
				<Tasks>
					<Script executionString="SELECT * FROM FACILITYSEARCH_ALL" />
				</Tasks>
			</Thread>
		</Threads>
	</Job>
</Jobs>

=== soravroyal/EPRTR/tags/deploy_2013_05_23_BM/Website/WebAppCode/Test/PerformanceTester/TestRunData2.xml
<?xml version="1.0" encoding="UTF-8"?>
<Jobs executionTime="60" commandTimeout="120" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\DOCUME~1\JKC\MYDOCU~1\EEA\SPPerformanceTester\SPPerformanceTester\TestRunData.xsd">
	<Job name="A1 - snapshot">
		<Threads>
			<Thread name="snapshot" Id="1" ThreadCopies="10">
				<Tasks>
					<StoredProcedure executionString="exec [giseditor].[XCP_GET_SNAPSHOT_XML]"/>
					<StoredProcedure executionString="exec giseditor.XCP_GET_STATION_DATA_XML @thresholdType, @eoi_code">
						<Parameters>
							<Parameter name="@thresholdType" value="1" valueType="int"/>
							<Parameter name="@eoi_code" value="DK0032A"/>
						</Parameters>
					</StoredProcedure>
					<StoredProcedure executionString="exec giseditor.XCP_GET_STATION_DATA_XML @thresholdType, @eoi_code">
						<Parameters>
							<Parameter name="@thresholdType" value="1" valueType="int"/>
							<Parameter name="@eoi_code" value="DK0011A"/>
						</Parameters>
					</StoredProcedure>
					<StoredProcedure executionString="exec giseditor.XCP_GET_STATION_DATA_XML @thresholdType, @eoi_code">
						<Parameters>
							<Parameter name="@thresholdType" value="1" valueType="int"/>
							<Parameter name="@eoi_code" value="DK0047A"/>
						</Parameters>
					</StoredProcedure>
				</Tasks>
			</Thread>
		</Threads>
	</Job>
	<Job name="A1 - explorer">
		<Threads>
			<Thread name="explorer" Id="2" ThreadCopies="10">
				<Tasks>
					<StoredProcedure executionString="exec giseditor.XCP_GET_EXPLORER_MONTHLY_XML @onlySemivalidated">
						<Parameters>
							<Parameter name="@onlySemivalidated" value="1" valueType="int"/>
						</Parameters>
					</StoredProcedure>
					<StoredProcedure executionString="exec giseditor.XCP_GET_EXPLORER_MONTHLY_XML @onlySemivalidated">
						<Parameters>
							<Parameter name="@onlySemivalidated" value="0" valueType="int"/>
						</Parameters>
					</StoredProcedure>
					<StoredProcedure executionString="exec giseditor.XCP_GET_EXPLORER_OUTPUT_XML @country, @treshold, @period, @status">
						<Parameters>
							<Parameter name="@country" value="DK"/>
							<Parameter name="@treshold" value="DK"/>
							<Parameter name="@period" value="-1" valueType="int"/>
							<Parameter name="@status" value="1" valueType="int"/>
						</Parameters>
					</StoredProcedure>
				</Tasks>
			</Thread>
		</Threads>
	</Job>
	<Job name="A1 - snapshot and explorer in parallel">
		<Threads>
			<ThreadRef Id="1" ThreadCopies="10"/>
			<ThreadRef Id="2" ThreadCopies="10"/>
		</Threads>
	</Job>
	<Job name="A2 - Admin">
		<Threads>
			<Thread name="Admin" Id="3" ThreadCopies="2">
				<Tasks>
					<StoredProcedure executionString="exec giseditor.XCP_GET_PROVIDER_XML @pName">
						<Parameters>
							<Parameter name="@pName" value="dk_dmu"/>
						</Parameters>
					</StoredProcedure>
					<StoredProcedure executionString="exec giseditor.XCP_UPDATE_PROVIDER_TRUST @fk_provider_id, @trust_flag">
						<Parameters>
							<Parameter name="@fk_provider_id" value="FA360FC8-5515-4C2E-82CF-4C3BCE4FA2F9"/>
							<Parameter name="@trust_flag" value="1" valueType="int"/>
						</Parameters>
					</StoredProcedure>
					<StoredProcedure executionString="exec giseditor.XCP_GET_PROVIDER_QC_XML @pName">
						<Parameters>
							<Parameter name="@pName" value="dk_dmu"/>
						</Parameters>
					</StoredProcedure>
					<StoredProcedure executionString="exec giseditor.XCP_UPDATE_QC_MONTHLY @station_sEoI_Code, @rapport_year, @april, @may, @june, @july, @august, @september">
						<Parameters>
							<Parameter name="@station_sEoI_Code" value="DK0011A"/>
							<Parameter name="@rapport_year " value="2007" valueType="int"/>
							<Parameter name="@april" value="1" valueType="int"/>
							<Parameter name="@may" value="1" valueType="int"/>
							<Parameter name="@june" value="1" valueType="int"/>
							<Parameter name="@july" value="1" valueType="int"/>
							<Parameter name="@august" value="1" valueType="int"/>
							<Parameter name="@september" value="1" valueType="int"/>
						</Parameters>
					</StoredProcedure>
					<Script executionString="use [sor]
declare @turn_off_id uniqueidentifier
delete from giseditor.turn_off  where fk_station_id = '36CA8A11-74A0-4F0A-B5F0-5C4480973D2E'
delete from giseditor.XC_IS_PUBLISHABLE_AUDIT where fk_station_id = '36CA8A11-74A0-4F0A-B5F0-5C4480973D2E'

exec giseditor.XCP_Data_turn_off_Insert 
	'System' , '2007-08-11 12:00:00' ,'2007-08-11 12:00:00' ,
	'FA360FC8-5515-4C2E-82CF-4C3BCE4FA2F9' , 
	'36CA8A11-74A0-4F0A-B5F0-5C4480973D2E' , 
	'4798DBA5-B63D-48B2-99DA-0AF89024C55E' , 
	'error in station','0','WOS'
exec giseditor.XCP_Data_turn_off_View '36CA8A11-74A0-4F0A-B5F0-5C4480973D2E'

set @turn_off_id = (select top 1 pk_turn_off_id from giseditor.turn_off where fk_station_id = '36CA8A11-74A0-4F0A-B5F0-5C4480973D2E')
exec giseditor.XCP_Data_turn_off_Delete @turn_off_id,'DELETE_USER'
exec giseditor.XCP_Data_turn_off_View '36CA8A11-74A0-4F0A-B5F0-5C4480973D2E'
"/>
				</Tasks>
			</Thread>
		</Threads>
	</Job>
	<Job name="A1 - snapshot and explorer and A2 in parallel">
		<Threads>
			<ThreadRef Id="1" ThreadCopies="2"/>
			<ThreadRef Id="2" ThreadCopies="10"/>
			<ThreadRef Id="3" ThreadCopies="10"/>
		</Threads>
	</Job>
<!--	<Job name="A3">
		<Threads>
			<Thread name="Nightly" Id="4">
				<Tasks>
					<Script executionString="exec giseditor.XCP_CREATE_SNAPSHOT_XML
exec giseditor.XCP_PrepareExplorerSemiValidatedXML 
exec giseditor.XCP_PrepareExplorerPreliminaryXML 
exec giseditor.XCP_CREATE_STATIC_MAP
exec giseditor.XCP_CREATE_PROVIDER_XML 'FA360FC8-5515-4C2E-82CF-4C3BCE4FA2F9'
exec giseditor.XCP_CREATE_SNAPSHOT_XML
exec giseditor.XCP_POPULATE_XC_MEASUREMENT_LTO
exec giseditor.XCP_POPULATE_XC_STATION_EXCEEDANCES_SEASON
exec giseditor.XCP_CREATE_EXPLORER_OUTPUT_XML"/>
				</Tasks>
			</Thread>
		</Threads>
	</Job>
	<Job name="A1 - snapshot and explorer and A3 in parallel">
		<Threads>
			<ThreadRef Id="1"/>
			<ThreadRef Id="2"/>
			<ThreadRef Id="4"/>
		</Threads>
	</Job>
	<Job name="A2 and A3 in parallel">
		<Threads>
			<ThreadRef Id="3"/>
			<ThreadRef Id="4"/>
		</Threads>
	</Job>
		<Threads>
			<ThreadRef Id="1" ThreadCopies="100"/>
			<ThreadRef Id="2" ThreadCopies="100"/>
			<ThreadRef Id="3" ThreadCopies="30"/>
		</Threads>
	</Job>-->
</Jobs>
